name: Release

on:
  push:
    branches: [release, beta]
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn add sharp --ignore-engines
      - run: yarn build
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: 'dc7290'
          GIT_AUTHOR_EMAIL: 'dhkh.cba0927@gmail.com'
          GIT_COMMITTER_NAME: 'dc7290'
          GIT_COMMITTER_EMAIL: 'dhkh.cba0927@gmail.com'
        run: yarn semantic-release
